module.exports = {
  home_title: 'Compagnie fiduciaire',
  error_mdp: 'Le mot de passe est incorrect.',
  error_email: 'Identifiants est incorrect.',
  not_found: 'User not found',
  invalid_date: 'Invalid date format',
  invalid_rib: 'Invalid rib',
  select_period: 'Choisir la période',
  from: 'Du',
  to: 'Au',
  select_rib: 'Choisir RIB',
  find: 'Rechercher',
  no_rib_saved: 'Aucun RIB trouvé',
  operation_trad: {
    rib: 'RIB: ',
    date: 'Date',
    libelle: 'Libelle',
    montant: 'Montant',
    recepe: 'Recettes',
    spent: 'Dépenses',
    recipe_atr: 'recipe',
    spent_atr: 'spent',
    sold: 'SOLDE:   ',
    cancel: 'Retour',
  },
};
